# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: pretty


title: qpalzz
email: same-as-domain{at}qpalzz.com
description: > # this means to ignore newlines until "baseurl:"
  Нормальный такой сайтец, как и все остальные,
  непонятно для чего сделан
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://qpalzz.com" # the base hostname & protocol for your site
github_username:  qpalzz

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      in_menu: "false"
      menu-order: 0